### ISSUE TITLE
Classes using ParameterService fail due to its visibility in newer Nuke.Common library

### ISSUE THREAD

**Issue by totollygeek** [nuke-build/azure-keyvault#7]
Attributes in the library still use the old way of using `ParameterService`, while it was still public.
Now that it is internal, they fail in runtime if you use it with newer version of Nuke.Common.

Suggested fix:
Replace code like `new ParameterService().GetParameter<string>(secretName)` with `EnvironmentInfo..GetParameter<string>(secretName)`.

**Comment by totollygeek** [comment]
Just saw there is already this pull request: #6, which will fix it. Close the issue when the request is merged.

**Comment by GeorgDangl** [comment]
Thanks for bringing it up😊
